apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cassandra-monitor
  labels:
    release: prometheus
    prometheus: prometheus-kube-prometheus-prometheus
spec:
  selector:
    matchLabels:
      app: cassandra
      service: metrics
  endpoints:
  - port: metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default