---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  selector:
    app: cassandra
  ports:
  - name: cql
    port: 9042
    targetPort: 9042
    protocol: TCP
  - name: intra-node
    port: 7000
    targetPort: 7000
    protocol: TCP
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-jmx-exporter
  labels:
    app: cassandra
spec:
  selector:
    app: cassandra
  ports:
  - name: jmx-exporter
    port: 9111
    targetPort: 9111
    protocol: TCP
  type: ClusterIP