apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  serviceName: cassandra
  replicas: 6
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: cassandra
        image: gcr.io/google-samples/cassandra:v13
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "500m"
            memory: 1Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command: 
              - /bin/sh
              - -c
              - nodetool drain
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: CASSANDRA_SEEDS
            value: "cassandra-0.cassandra.default.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "K8Demo"
          - name: CASSANDRA_DC
            value: "DC1-K8Demo"
          - name: CASSANDRA_RACK
            value: "Rack1-K8Demo"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /ready-probe.sh
          initialDelaySeconds: 30
          timeoutSeconds: 30
        volumeMounts:
        - name: cassandra-data
          mountPath: /cassandra_data
      - name: jmx-exporter
        image: prometheus/jmx-exporter:v0.16.1
        ports:
        - containerPort: 9111
          name: jmx-exporter
          protocol: TCP
        env:
        - name: JAVA_AGENT
          value: -javaagent:/jmx-exporter/jmx_prometheus_javaagent.jar=port=9111,config.file=/config/config.yaml
        volumeMounts:
        - name: jmx-config
          mountPath: /config
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-storage
      resources:
        requests:
          storage: 1Gi
  volumes:
  - name: jmx-config
    configMap:
      name: jmx-exporter-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jmx-exporter-config
  labels:
    app: cassandra
data:
  config.yaml: |
    startDelaySeconds: 10
    ssl: false
    lowercaseOutputName: true
    rules:
      - pattern: "org.apache.cassandra.metrics<type=(Table|ColumnFamily), name=.*>"
        name: "cassandra_$1_$2"
      - pattern: "org.apache.cassandra.metrics<type=ClientRequest, name=.*Latency>"
        name: "cassandra_$1_latency"
      # Add more rules as needed for the metrics you want to expose

